let produtos = [
    {
      "Peso":0,
      "CodigoBarra":"12068502134/38",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":14,
      "QuantidadeReservada":14
    },
    {
      "Peso":0,
      "CodigoBarra":"12068502139/44",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":5,
      "QuantidadeReservada":5
    },
    {
      "Peso":0,
      "CodigoBarra":"12068556234/38",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":9,
      "QuantidadeReservada":9
    },
    {
      "Peso":0,
      "CodigoBarra":"12068556239/44",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"121808006739",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"12230600437",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"12254111841",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"12262106140",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"12308302128",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"123083371529",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    },
    {
      "Peso":0,
      "CodigoBarra":"123325006740",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":4,
      "QuantidadeReservada":4
    },
    {
      "Peso":0,
      "CodigoBarra":"7909403548214",
      "EstoqueDestino":null,
      "QuantidadeVolume":null,
      "QuantidadeOriginal":1,
      "QuantidadeReservada":1
    }
  ]

  let sum = 0;

  for (produto of produtos) {
    sum += produto.QuantidadeReservada
  }

  console.log(sum);